---
version: "3.9"
services:
  tvheadend:
    image: ghcr.io/linuxserver/tvheadend
    container_name: aurora-tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /home/bios/Docker/Containers/AppData/t/tvheadend:/config
      - /home/bios/Docker/Containers/AppData/t/tvheadend/recoridngs:/recordings
#    ports:
#      - 9981:9981
#      - 9982:9982
    restart: unless-stopped

networks:
    default:
      external:
        name: internalized