---
version: "3.9"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: aurora-nzbget
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Australia/Melbourne
    volumes:
        - /home/bios/Docker/Containers/AppData/n/nzbget:/config
        - /home/bios/Docker/Data/Downloads:/downloads
    #ports:
    #    - 6789:6789
    restart: unless-stopped
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: aurora-qbittorrent
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Australia/Melbourne
        - UMASK_SET=022
        - WEBUI_PORT=9080
    volumes:
        - /home/bios/Docker/Containers/AppData/q/qbittorrent:/config
        - /home/bios/Docker/Data/Downloads:/downloads
    #ports:
    #    - 6881:6881
    #    - 6881:6881/udp
    #    - 8080:8080
    restart: unless-stopped
    
networks:
    default:
      external:
        name: internalized