---
version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: aurora-jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - AUTO_UPDATE=true
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/bios/Docker/Containers/AppData/j/jackett:/config
#    ports:
#      - 9117:9117
    restart: unless-stopped
  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: aurora-nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /home/bios/Docker/Containers/AppData/n/nzbhydra2:/config
      - /home/bios/Docker/Data/Downloads:/downloads
#    ports:
#      - 5076:5076
    restart: unless-stopped

networks:
    default:
      external:
        name: internalized